"""
Build Task 3, 4, 5 notebooks
"""
import nbformat as nbf
import os

os.makedirs('/opt/data/capstone/notebooks', exist_ok=True)

# ─────────────────────────────────────────────────────────────────────────────
# TASK 3 NOTEBOOK
# ─────────────────────────────────────────────────────────────────────────────
nb3 = nbf.v4.new_notebook()
nb3.metadata = {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}}

cells3 = []

cells3.append(nbf.v4.new_markdown_cell(
"# Task 3 - Solution Design and Integration Gap Analysis\n"
"## AI-Augmented Business Analyst Capstone\n"
"**Company:** Meridian Financial | **Scenario:** FCA KYC/AML Onboarding Remediation\n"
"**Inputs Required:** `functional_requirements.csv`, `requirements_backlog.csv`, `gap_requirement_traceability.csv`\n"
"---\n"
"## Overview\n"
"You have received the email from James Okafor. Engineering has flagged that not all requirements can be delivered in 10 weeks with 3 engineers, and the Salesforce FSC configuration cannot support some requirements without significant customisation.\n"
"\n"
"By the end of this notebook you will have produced:\n"
"1. **Requirements-to-Systems Mapping** (which system implements each requirement)\n"
"2. **Integration Gap Analysis** (new/changed integrations and their risks)\n"
"3. **Solution Options Assessment** (Build / Buy / Configure / Integrate)\n"
"4. **Data Model Gap Analysis** (new data entities needed)\n"
"---\n"
))

cells3.append(nbf.v4.new_markdown_cell("## 1. Load Prior Outputs\n"))
cells3.append(nbf.v4.new_code_cell(
"import pandas as pd\n"
"import os\n"
"os.makedirs('../outputs', exist_ok=True)\n"
"\n"
"df_fr = pd.read_csv('../outputs/functional_requirements.csv')\n"
"df_nfr = pd.read_csv('../outputs/non_functional_requirements.csv')\n"
"df_backlog = pd.read_csv('../outputs/requirements_backlog.csv')\n"
"\n"
"print('Loaded FRs:', len(df_fr))\n"
"print('Loaded NFRs:', len(df_nfr))\n"
"print('Loaded backlog items:', len(df_backlog))\n"
"\n"
"# Sprint 1 scope\n"
"print()\n"
"sprint1 = df_backlog[df_backlog['assigned_sprint']=='Sprint 1']\n"
"print('Sprint 1 scope:', len(sprint1), 'items')\n"
))

cells3.append(nbf.v4.new_markdown_cell(
"## 2. Requirements-to-Systems Mapping\n"
"\n"
"### Framework\n"
"\n"
"For each Sprint 1 requirement, identify:\n"
"- **Primary System**: The system that must implement the requirement\n"
"- **Supporting Systems**: Systems that must integrate or provide data\n"
"- **Integration Type**: Build new / Extend existing / Integrate third-party\n"
"- **Data Inputs**: What data the requirement needs from other systems\n"
"- **Data Outputs**: What data the requirement produces for other systems\n"
"\n"
"> **Activity:** Complete the mapping table below. Use Prompt 3.2 to assess integration risks.\n"
))

cells3.append(nbf.v4.new_code_cell(
"# COMPLETE THE MAPPING TABLE\n"
"\n"
"mapping_data = {\n"
"    'req_id': ['FR-001','FR-002','FR-003','FR-004','FR-005','NFR-001','NFR-002'],\n"
"    'requirement_title': [\n"
"        'Mandatory Beneficial Ownership Declaration',\n"
"        'Automated PEP and Sanctions Screening',\n"
"        'Identity Verification Evidence Capture',\n"
"        'Automated Compliance Audit Log',\n"
"        'Client Risk Rating at Application Submission',\n"
"        'Audit Log Retention - 5 Years',\n"
"        'API Response Time <= 30 Seconds'\n"
"    ],\n"
"    'primary_system': [\n"
"        'Onboarding Microservice',\n"
"        'Onboarding Microservice',\n"
"        'Onboarding Microservice',\n"
"        'Onboarding Microservice + Audit DB',\n"
"        'Onboarding Microservice',\n"
"        'Audit DB (PostgreSQL)',\n"
"        'Onboarding Microservice'\n"
"    ],\n"
"    'supporting_systems': [\n"
"        'Salesforce FSC, Companies House API',\n"
"        'Dow Jones API, Salesforce FSC',\n"
"        'Experian Verify API',\n"
"        'Salesforce FSC',\n"
"        'Salesforce FSC',\n"
"        'N/A',\n"
"        'Experian Verify API'\n"
"    ],\n"
"    'integration_type': [\n"
"        'Build new + Configure',\n"
"        'Extend existing (Dow Jones integration)',\n"
"        'Extend existing (Experian integration)',\n"
"        'Build new',\n"
"        'Build new',\n"
"        'Configure existing',\n"
"        'Optimise existing'\n"
"    ],\n"
"    'implementation_approach': [\n"
"        'Build',\n"
"        'Build',\n"
"        'Build',\n"
"        'Build',\n"
"        'Build',\n"
"        'Configure',\n"
"        'Optimise'\n"
"    ],\n"
"    'integration_risk': ['High','High','Medium','High','Medium','Low','Medium'],\n"
"    'new_integration_required': ['Yes','Yes','No','Yes','No','No','No']\n"
"}\n"
"\n"
"df_mapping = pd.DataFrame(mapping_data)\n"
"print('Requirements-to-Systems Mapping')\n"
"print('='*60)\n"
"df_mapping[['req_id','primary_system','integration_type','integration_risk']]\n"
))

cells3.append(nbf.v4.new_markdown_cell("## 3. Integration Gap Analysis\n"))

cells3.append(nbf.v4.new_code_cell(
"# INTEGRATION GAPS - complete for each new/changed integration\n"
"\n"
"int_gaps = {\n"
"    'int_id': ['IG-001','IG-002','IG-003','IG-004'],\n"
"    'integration_name': [\n"
"        'BO Declaration - Companies House API',\n"
"        'Onboarding Microservice - Salesforce FSC Sync',\n"
"        'Audit Log - Salesforce FSC',\n"
"        'Dow Jones API - PEP/Sanctions Screening'\n"
"    ],\n"
"    'current_state': [\n"
"        'Manual email-based BO lookup',\n"
"        'Basic account data sync (one-way)',\n"
"        'Manual CSV export from Salesforce to Compliance team',\n"
"        'Manual execution by Diana in Dow Jones web interface'\n"
"    ],\n"
"    'required_state': [\n"
"        'Automated API call to Companies House to verify BO entity details in real time',\n"
"        'Bidirectional real-time sync: Salesforce FSC <-> Onboarding Microservice',\n"
"        'Automated audit log entries synced from Onboarding Microservice to Salesforce FSC compliance module',\n"
"        'Automated API call triggered at application submission, result stored in compliance record'\n"
"    ],\n"
"    'gap_description': [\n"
"        'No API integration with Companies House currently exists. BO verification is manual and inconsistent.',\n"
"        'The Microservice was not designed for bidirectional real-time sync. Requires significant redesign.',\n"
"        'No automated flow exists. Compliance team relies on manual exports for FCA reviews.',\n"
"        'No automated trigger exists. PEP screening depends on manual execution by Diana.'\n"
"    ],\n"
"    'integration_risk': ['High','High','High','High'],\n"
"    'third_party_dependency': ['Yes - Companies House','No','No','Yes - Dow Jones'],\n"
"    'fallback_procedure': [\n"
"        'Manual lookup and documented telephone confirmation with Companies House',\n"
"        'Operations team manually creates record in Salesforce FSC within 4 hours',\n"
"        'Manual Salesforce report export - acceptable for max 2 weeks during transition',\n"
"        'Diana manually executes Dow Jones check - 48-hour SLA for result'\n"
"    ]\n"
"}\n"
"\n"
"df_int_gaps = pd.DataFrame(int_gaps)\n"
"print('Integration Gap Analysis')\n"
"print('='*60)\n"
"df_int_gaps[['int_id','integration_name','integration_risk','third_party_dependency']]\n"
))

cells3.append(nbf.v4.new_markdown_cell(
"## 4. Solution Options Assessment\n"
"\n"
"For the three largest technical gaps, assess solution options.\n"
"\n"
"> **Activity:** Complete the options tables below. Use Prompt 3.1 to research vendors.\n"
"\n"
"### Gap 1: Beneficial Ownership Verification\n"
"\n"
"| Option | Description | Pros | Cons | Est. Effort | Est. Cost | Risk | Recommendation |\n"
"|--------|-------------|------|------|-------------|-----------|------|----------------|\n"
"| A: Build In-House | Custom form + manual Companies House lookup | Full control | Slow, high effort | High | High | Low | Reject - timeline |\n"
"| B: Companies House API | Automated API call to Companies House | Fast, compliant | API coverage limited | Medium | Low | Medium | Evaluate |\n"
"| C: Third-Party BO Platform | Kyckr or Enumacloud integration | Fast, comprehensive | Vendor lock-in | Low | Medium | Low | Evaluate |\n"
"\n"
"### Gap 2: Salesforce FSC - Microservice Sync\n"
"\n"
"| Option | Description | Pros | Cons | Est. Effort | Risk | Recommendation |\n"
"|--------|-------------|------|------|-------------|------|----------------|\n"
"| A: Custom Sync Service | Build a new bidirectional sync layer | Full control | High effort, 6+ weeks | High | High | Reject - timeline |\n"
"| B: Salesforce FSC Out-of-the-Box | Use Salesforce FSC workflows with minimal customisation | Low effort | Cannot support all requirements | Low | High | Reject - gaps remain |\n"
"| C: MuleSoft / iPaaS Connector | Integrate via MuleSoft or similar iPaaS | Faster than custom, reliable | Additional vendor | Medium | Medium | Evaluate |\n"
"\n"
"### Gap 3: PEP/Sanctions Screening\n"
"\n"
"| Option | Description | Pros | Cons | Est. Effort | Risk | Recommendation |\n"
"|--------|-------------|------|------|-------------|------|----------------|\n"
"| A: Manual Dow Jones (Status Quo) | Diana manually runs Dow Jones | No change | Not scalable, error-prone | None | Very High | Reject - regulatory risk |\n"
"| B: Automated Dow Jones API | Extend current Dow Jones subscription to API | Automated, uses existing vendor | API cost increase | Low | Low | Recommended |\n"
"| C: Alternative Platform | Switch to another screening provider | May be better value | Migration effort, new vendor review | High | Medium | Evaluate for Sprint 2 |\n"
))

cells3.append(nbf.v4.new_markdown_cell("## 5. Data Model Gap Analysis\n"))

cells3.append(nbf.v4.new_code_cell(
"# DATA ENTITIES - what new data do we need to capture?\n"
"\n"
"entity_data = {\n"
"    'entity_name': ['BeneficialOwner','ComplianceAuditEntry','RiskRatingRecord','PEPcreeningResult'],\n"
"    'description': [\n"
"        'Individual who owns or controls >=25% of client entity',\n"
"        'Immutable record of a compliance check performed during onboarding',\n"
"        'Automated risk score assigned at application submission',\n"
"        'Result of automated PEP/sanctions screening check'\n"
"    ],\n"
"    'key_fields': [\n"
"        'Full name, DOB, Nationality, Address, Ownership %, Role, BO declaration date',\n"
"        'Timestamp, Actor, Action, Outcome, Evidence ref, Client ID, Compliance officer ID',\n"
"        'Score (0-100), Rating (Low/Med/High), Rules applied, Review date, Officer',\n"
"        'Check date, API response, Match result (true/false), Match details, Dow Jones ref'\n"
"    ],\n"
"    'source_system': ['Client / Companies House API','Onboarding Microservice','Onboarding Microservice','Onboarding Microservice'],\n"
"    'target_system': ['Onboarding Microservice -> Salesforce FSC','Audit DB -> Salesforce FSC','Onboarding Microservice -> Salesforce FSC','Onboarding Microservice'],\n"
"    'exists_in_current_model': ['No','No','No','No'],\n"
"    'data_model_gap': [\n"
"        'No BO entity exists in current data model - must be created',\n"
"        'No central audit store - currently scattered across email and Salesforce notes',\n"
"        'Risk rating not stored as a data entity - currently a spreadsheet field',\n"
"        'PEP result not stored as a data entity - Diana records results in Dow Jones web only'\n"
"    ]\n"
"}\n"
"\n"
"df_entities = pd.DataFrame(entity_data)\n"
"print('New Data Entities Required')\n"
"print('='*60)\n"
"df_entities[['entity_name','exists_in_current_model']]\n"
))

cells3.append(nbf.v4.new_markdown_cell("## 6. System Context Diagram\n"))

cells3.append(nbf.v4.new_code_cell(
"import matplotlib.pyplot as plt\n"
"import matplotlib.patches as mpatches\n"
"from matplotlib.patches import FancyBboxPatch\n"
"\n"
"fig, ax = plt.subplots(figsize=(16, 11))\n"
"ax.set_xlim(0, 16)\n"
"ax.set_ylim(0, 11)\n"
"ax.axis('off')\n"
"ax.set_title('Meridian Financial - Proposed Solution Architecture (Sprint 1)',\n"
"             fontsize=14, fontweight='bold', pad=15)\n"
"\n"
"# System boxes\n"
"systems = {\n"
"    'CLIENT': (8, 9.5),\n"
"    'Web Portal\\n(React)': (8, 8),\n"
"    'API Gateway': (8, 6.5),\n"
"    'Onboarding\\nMicroservice': (5, 5),\n"
"    'Salesforce\\nFSC': (11, 5),\n"
"    'Experian\\nVerify API': (1.5, 3),\n"
"    'Dow Jones\\nRisk Intel API': (5, 3),\n"
"    'Companies House\\nAPI': (8.5, 3),\n"
"    'Audit DB\\n(PostgreSQL)': (12, 3),\n"
"    'Core Banking\\nSystem': (8, 1),\n"
"}\n"
"\n"
"colors = {\n"
"    'CLIENT': '#E8EAF6',\n"
"    'Web Portal\\n(React)': '#E3F2FD',\n"
"    'API Gateway': '#E3F2FD',\n"
"    'Onboarding\\nMicroservice': '#FFF9C4',\n"
"    'Salesforce\\nFSC': '#E8F5E9',\n"
"    'Experian\\nVerify API': '#FCE4EC',\n"
"    'Dow Jones\\nRisk Intel API': '#FCE4EC',\n"
"    'Companies House\\nAPI': '#FCE4EC',\n"
"    'Audit DB\\n(PostgreSQL)': '#E8F5E9',\n"
"    'Core Banking\\nSystem': '#E8F5E9',\n"
"}\n"
"\n"
"for name, (x, y) in systems.items():\n"
"    color = colors.get(name, '#E0E0E0')\n"
"    box = FancyBboxPatch((x-1.4, y-0.7), 2.8, 1.4,\n"
"                         boxstyle='round,pad=0.1',\n"
"                         facecolor=color, edgecolor='#333', linewidth=1.5)\n"
"    ax.add_patch(box)\n"
"    ax.text(x, y, name, ha='center', va='center', fontsize=8, fontweight='bold')\n"
"\n"
"# Arrows\n"
"arrow_props = dict(arrowstyle='->', color='#333', lw=1.3)\n"
"\n"
"# Client -> Web Portal\n"
"ax.annotate('', xy=(8, 8.7), xytext=(8, 9.2), arrowprops=arrow_props)\n"
"\n"
"# Web Portal -> API Gateway\n"
"ax.annotate('', xy=(8, 7.1), xytext=(8, 7.4), arrowprops=arrow_props)\n"
"\n"
"# API Gateway -> Microservice\n"
"ax.annotate('', xy=(5.7, 5.4), xytext=(6.3, 6.3), arrowprops=arrow_props)\n"
"ax.text(5.2, 6, 'POST /apply', fontsize=6, color='#555')\n"
"\n"
"# API Gateway -> Salesforce FSC\n"
"ax.annotate('', xy=(9.6, 5.4), xytext=(9.3, 6.3), arrowprops=arrow_props)\n"
"ax.text(9.8, 6, 'API', fontsize=6, color='#555')\n"
"\n"
"# Microservice -> Experian\n"
"ax.annotate('', xy=(2.5, 3.4), xytext=(4.2, 4.4), arrowprops=arrow_props)\n"
"ax.text(2.5, 4.2, 'Verify API', fontsize=6, color='#555')\n"
"\n"
"# Microservice -> Dow Jones\n"
"ax.annotate('', xy=(5.8, 3.4), xytext=(5.2, 4.4), arrowprops=arrow_props)\n"
"ax.text(4.5, 4.2, 'PEP API', fontsize=6, color='#555')\n"
"\n"
"# Microservice -> Companies House\n"
"ax.annotate('', xy=(7.7, 3.4), xytext=(5.8, 4.4), arrowprops=arrow_props)\n"
"\n"
"# Microservice -> Audit DB\n"
"ax.annotate('', xy=(11.2, 3.4), xytext=(6.2, 4.4), arrowprops=arrow_props)\n"
"ax.text(8.5, 4.2, 'Audit log', fontsize=6, color='#555')\n"
"\n"
"# Microservice -> Core Banking\n"
"ax.annotate('', xy=(7.2, 1.4), xytext=(5.8, 4.3), arrowprops=arrow_props)\n"
"\n"
"# Legend\n"
"legend_elements = [\n"
"    mpatches.Patch(facecolor='#E3F2FD', edgecolor='#333', label='Client-facing'),\n"
"    mpatches.Patch(facecolor='#FFF9C4', edgecolor='#333', label='Core System (Build)'),\n"
"    mpatches.Patch(facecolor='#E8F5E9', edgecolor='#333', label='Existing System'),\n"
"    mpatches.Patch(facecolor='#FCE4EC', edgecolor='#333', label='Third-Party API (Buy/Integrate)'),\n"
"]\n"
"ax.legend(handles=legend_elements, loc='upper right', fontsize=8)\n"
"\n"
"plt.tight_layout()\n"
"plt.savefig('../outputs/solution_architecture.png', dpi=150, bbox_inches='tight')\n"
"plt.show()\n"
"print('Saved: ../outputs/solution_architecture.png')\n"
))

cells3.append(nbf.v4.new_markdown_cell("## 7. Export Outputs\n"))

cells3.append(nbf.v4.new_code_cell(
"df_mapping.to_csv('../outputs/requirements_systems_mapping.csv', index=False)\n"
"df_int_gaps.to_csv('../outputs/integration_gap_analysis.csv', index=False)\n"
"df_entities.to_csv('../outputs/data_model_gaps.csv', index=False)\n"
"\n"
"print('Exported:')\n"
"for f in ['requirements_systems_mapping.csv','integration_gap_analysis.csv','data_model_gaps.csv']:\n"
"    print('  -', f)\n"
))

cells3.append(nbf.v4.new_markdown_cell(
"## AI Prompt Library - Task 3\n"
"\n"
"### Prompt 3.1: Vendor Research\n"
"\n"
"```\n"
"You are a Market Intelligence Analyst for UK financial services compliance tech.\n"
"\n"
"Research and compare: KYC/ID verification platforms (Onfido, Jumio, Veriff), BO verification\n"
"platforms (Kyckr, Enumacloud, Companies House API), and PEP/sanctions alternatives to Dow Jones.\n"
"\n"
"For each: pricing model, FCA compliance history, UK presence, integration complexity.\n"
"\n"
"Format as comparison table. Flag: do not invent pricing - provide ranges.\n"
"```\n"
"\n"
"### Prompt 3.2: Integration Risk Assessment\n"
"\n"
"```\n"
"You are a Solutions Architect reviewing integration complexity.\n"
"\n"
"Current: Salesforce FSC + Onboarding Microservice (3yr old, limited docs) + Experian API + Dow Jones API.\n"
"\n"
"Proposed: New BO declaration form, automated PEP screening, audit log, Companies House API integration.\n"
"\n"
"Assess: integration complexity, likely technical challenges with Salesforce sync,\n"
"data transformation needs, fallback procedures, security considerations, and testing approach.\n"
"```\n"
))

nb3.cells = cells3
with open('/opt/data/capstone/notebooks/Task_3_Solution_Design.ipynb', 'w') as f:
    nbf.write(nb3, f)
print("Task 3 notebook written")

# ─────────────────────────────────────────────────────────────────────────────
# TASK 4 NOTEBOOK
# ─────────────────────────────────────────────────────────────────────────────
nb4 = nbf.v4.new_notebook()
nb4.metadata = {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}}

cells4 = []

cells4.append(nbf.v4.new_markdown_cell(
"# Task 4 - UAT Planning and Test Scenario Design\n"
"## AI-Augmented Business Analyst Capstone\n"
"**Company:** Meridian Financial | **Scenario:** FCA KYC/AML Onboarding Remediation\n"
"**Inputs Required:** `functional_requirements.csv`, `requirements_systems_mapping.csv`\n"
"---\n"
"## Overview\n"
"You have received the email from Diana Vlasova (Lead Engineer). Engineering is ready to build Sprint 1. Diana needs a UAT test strategy and full test scenario outlines for every Sprint 1 requirement.\n"
"\n"
"By the end of this notebook you will have produced:\n"
"1. A **UAT Test Strategy** document\n"
"2. **Test Scenario Register** with happy, alternative, and failure paths\n"
"3. A **Traceability Matrix** linking requirements to test scenarios\n"
"\n"
"| Sprint 1 Scope | Req ID | Type |\n"
"|----------------|--------|------|\n"
"| Mandatory BO Declaration | FR-001 | FR |\n"
"| Automated PEP/Sanctions Screening | FR-002 | FR |\n"
"| Identity Verification Evidence Capture | FR-003 | FR |\n"
"| Automated Compliance Audit Log | FR-004 | FR |\n"
"| Client Risk Rating at Application | FR-005 | FR |\n"
"| Audit Log Retention 5 Years | NFR-001 | NFR |\n"
"| API Response Time <= 30s | NFR-002 | NFR |\n"
"| WCAG 2.1 AA Accessibility | NFR-005 | NFR |\n"
"---\n"
))

cells4.append(nbf.v4.new_markdown_cell("## 1. Load Inputs\n"))
cells4.append(nbf.v4.new_code_cell(
"import pandas as pd\n"
"import os\n"
"os.makedirs('../outputs', exist_ok=True)\n"
"\n"
"df_fr = pd.read_csv('../outputs/functional_requirements.csv')\n"
"df_mapping = pd.read_csv('../outputs/requirements_systems_mapping.csv')\n"
"\n"
"sprint1_reqs = df_fr[df_fr['priority'].isin(['Must Have','Should Have'])]\n"
"print('Sprint 1 requirements:', len(sprint1_reqs))\n"
"sprint1_reqs[['req_id','title','priority']]\n"
))

cells4.append(nbf.v4.new_markdown_cell(
"## 2. UAT Test Strategy\n"
"\n"
"### 2.1 Scope\n"
"\n"
"**In Scope:**\n"
"- All Sprint 1 functional requirements (FR-001 to FR-005)\n"
"- Sprint 1 non-functional requirements (NFR-001, NFR-002, NFR-005)\n"
"- Integration testing across: Web Portal, Onboarding Microservice, Salesforce FSC, Experian API, Dow Jones API\n"
"\n"
"**Out of Scope:**\n"
"- Sprint 2 requirements\n"
"- Regression testing of existing (unmodified) flows\n"
"- Performance/load testing (deferred to Sprint 2)\n"
"- Security penetration testing (separate engagement, scheduled separately)\n"
"\n"
"### 2.2 Testing Types\n"
"\n"
"| Type | Description | When |\n"
"|------|-------------|------|\n"
"| Functional Testing | Does the feature work as specified? | Each sprint |\n"
"| Integration Testing | Do systems communicate correctly end-to-end? | After each integration |\n"
"| Failure Handling Testing | What happens when things go wrong? | Each sprint |\n"
"| Data Validation Testing | Are inputs validated at the system boundary? | Each sprint |\n"
"| Exploratory Testing | What else might break? | End of sprint |\n"
"\n"
"### 2.3 Defect Severity Definitions\n"
"\n"
"| Severity | Definition | Resolution SLA |\n"
"|----------|------------|---------------|\n"
"| P1 - Critical | System unusable, data loss, security breach, FCA reportable | 24 hours |\n"
"| P2 - High | Major feature broken, workaround exists but painful | 3 days |\n"
"| P3 - Medium | Feature partially broken, minor workaround available | 1 week |\n"
"| P4 - Low | Cosmetic issue, no impact on functionality | Next sprint |\n"
"\n"
"### 2.4 UAT Entry Criteria\n"
"\n"
"- [ ] All P1 and P2 development defects closed\n"
"- [ ] Environment (UAT) provisioned and accessible\n"
"- [ ] Test data prepared for all scenarios\n"
"- [ ] Build signed off by Diana (Tech Lead)\n"
"- [ ] Test scenarios reviewed and signed off by James (Product)\n"
"\n"
"### 2.5 UAT Exit Criteria\n"
"\n"
"- [ ] All P1/P2 defects closed\n"
"- [ ] All critical path test scenarios passed\n"
"- [ ] Traceability matrix confirmed (100% coverage)\n"
"- [ ] Sign-off received from Sarah Chen (Compliance)\n"
"- [ ] UAT summary report produced\n"
))

cells4.append(nbf.v4.new_markdown_cell("## 3. Test Scenario Register\n"))

cells4.append(nbf.v4.new_markdown_cell(
"> **Activity:** Complete the test scenario register. For each requirement, write:\n"
"> - Happy path scenario (everything works correctly)\n"
"> - Alternative path (normal variation)\n"
"> - Failure path (something goes wrong)\n"
"> \n"
"> Use **Prompt 4.1** to generate drafts from acceptance criteria.\n"
"> Use **Prompt 4.2** for cross-system failure scenarios.\n"
))

cells4.append(nbf.v4.new_code_cell(
"# TEST SCENARIO REGISTER\n"
"\n"
"scenarios = {\n"
"    'ts_id': ['TS-FR001-001','TS-FR001-002','TS-FR001-003',\n"
"              'TS-FR002-001','TS-FR002-002','TS-FR002-003',\n"
"              'TS-FR003-001','TS-FR003-002','TS-FR003-003',\n"
"              'TS-FR004-001','TS-FR004-002','TS-FR004-003',\n"
"              'TS-FR005-001','TS-FR005-002','TS-FR005-003'],\n"
"    'req_id': ['FR-001','FR-001','FR-001',\n"
"               'FR-002','FR-002','FR-002',\n"
"               'FR-003','FR-003','FR-003',\n"
"               'FR-004','FR-004','FR-004',\n"
"               'FR-005','FR-005','FR-005'],\n"
"    'scenario_type': ['Happy Path','Alternative Path','Failure Path']*5,\n"
"    'title': [\n"
"        # FR-001 BO Declaration\n"
"        'BO Declaration - All Fields Completed Successfully',\n"
"        'BO Declaration - Partial Ownership (two 25% owners)',\n"
"        'BO Declaration - Missing Mandatory Field (ownership % blank)',\n"
"        # FR-002 PEP Screening\n"
"        'PEP Screening - No Match Found',\n"
"        'PEP Screening - API Timeout (Dow Jones unavailable)',\n"
"        'PEP Screening - True Positive Match Returned',\n"
"        # FR-003 ID Verification\n"
"        'ID Verification - Pass (Experian returns pass)',\n"
"        'ID Verification - Manual Review Required',\n"
"        'ID Verification - Experian API Returns Error',\n"
"        # FR-004 Audit Log\n"
"        'Audit Log - Entry Created on BO Declaration Submit',\n"
"        'Audit Log - Salesforce FSC Sync Failure (retry mechanism)',\n"
"        'Audit Log - Audit Record Integrity Check',\n"
"        # FR-005 Risk Rating\n"
"        'Risk Rating - Low Risk Client Assigned Correctly',\n"
"        'Risk Rating - PEP Match Escalates to High Risk',\n"
"        'Risk Rating - Incomplete Data Defaults to Medium Pending'\n"
"    ],\n"
"    'preconditions': [\n"
"        'Client is logged into onboarding portal, entity application form complete',\n"
"        'Client entity has two owners each with exactly 25% share',\n"
"        'Client attempts to submit BO declaration with Ownership % field empty',\n"
"        'Client has submitted application with no PEP risk indicators',\n"
"        'Dow Jones API returns HTTP 503 during PEP screening',\n"
"        'Dow Jones API returns a confirmed PEP match for a named BO individual',\n"
"        'Client submits valid passport and proof of address',\n"
"        'Experian returns "refer" - unable to verify automatically',\n"
"        'Experian API returns HTTP 500 after 25 seconds',\n"
"        'Client submits BO declaration successfully',\n"
"        'Onboarding Microservice cannot reach Salesforce FSC during audit sync',\n"
"        'Audit log record retrieved and hash verified against stored hash',\n"
"        'Client has UK entity, no PEP match, ID verification passed',\n"
"        'Client BO individual returns a confirmed PEP match',\n"
"        'Risk scoring rules engine receives application with missing nationality field'\n"
"    ],\n"
"    'test_steps': [\n"
"        '1. Client navigates to BO declaration screen\\n2. Client enters all mandatory BO fields\\n3. Client submits declaration\\n4. System validates all fields\\n5. System stores BO record\\n6. Account proceeds to next step',\n"
"        '1. Client enters two BO individuals each with 25% ownership\\n2. Client submits\\n3. System validates and accepts 25% as valid threshold\\n4. BO record stored correctly',\n"
"        '1. Client leaves Ownership % field blank\\n2. Client attempts submit\\n3. System displays mandatory field error\\n4. Account is NOT activated\\n5. Client cannot proceed without completing field',\n"
"        '1. Application submitted with named BO individuals\\n2. System calls Dow Jones API for each individual\\n3. API returns no match for all individuals\\n4. PEP screening result stored\\n5. Onboarding proceeds',\n"
"        '1. Application submitted\\n2. System calls Dow Jones API\\n3. API times out after 30 seconds\\n4. System triggers fallback procedure alert\\n5. Diana is notified within 5 minutes\\n6. Manual screening initiated with 48-hour SLA',\n"
"        '1. Application submitted\\n2. Dow Jones API returns true positive PEP match\\n3. System flags client as High Risk\\n4. Account moved to Compliance Review queue\\n5. Email alert sent to Sarah Chen\\n6. Onboarding paused until manual review complete',\n"
"        '1. Client uploads passport and proof of address\\n2. System calls Experian Verify API\\n3. API returns pass\\n4. Verification result stored in compliance record\\n5. ID verification step marked as complete',\n"
"        '1. Client uploads documents\\n2. Experian returns refer for manual review\\n3. System flags for manual ID check\\n4. Operations team notified\\n5. Manual review completed within 48 hours\\n6. Result entered by Operations team',\n"
"        '1. Client uploads documents\\n2. System calls Experian API\\n3. API returns HTTP 500 at 25 seconds\\n4. System retries once\\n5. Second attempt fails\\n6. System triggers Operations alert\\n7. Fallback: manual ID check within 24 hours',\n"
"        '1. Client submits BO declaration\\n2. Onboarding Microservice creates audit log entry\\n3. Entry synced to Audit DB\\n4. Entry synced to Salesforce FSC compliance module\\n5. Audit log entry verified in Salesforce FSC',\n"
"        '1. Audit log entry created in Microservice\\n2. Salesforce FSC sync fails (connection timeout)\\n3. System retries automatically 3 times\\n4. After 3 failures, Operations alert triggered\\n5. Audit entry held in Microservice with retry flag\\n6. Sync completes when Salesforce FSC available\\n7. No data lost',\n"
"        '1. Audit log entry retrieved from Audit DB\\n2. SHA-256 hash computed\\n3. Hash compared to stored hash\\n4. Match confirmed - record has not been altered\\n5. Audit trail integrity confirmed',\n"
"        '1. Application submitted: UK entity, no PEP match, ID verified, BO declared\\n2. Risk scoring rules engine evaluates application\\n3. Score computed based on: country=UK (+10), entity type=Ltd (+5), BO nationality=UK (+5), PEP=clear (+20), ID=pass (+10)\\n4. Total score = 50 (Low Risk threshold: 0-40 = High, 41-70 = Medium, 71+ = Low)\\n5. Wait - score 50 = Medium Risk\\n6. Correct rating applied',\n"
"        '1. Application: BO individual returns confirmed PEP match\\n2. Risk scoring rules: PEP match adds 60 points\\n3. Score = 60 (above High Risk threshold of 50)\\n4. Account flagged as High Risk\\n5. Correct escalation to Compliance Review',\n"
"        '1. Application submitted with missing BO nationality field\\n2. Risk scoring engine receives null for nationality\\n3. Engine applies default: score = 40 (Medium Risk pending)\\n4. Application flagged as requiring data completion\\n5. Client notified to provide missing data\\n6. Risk score updated once data received'\n"
"    ],\n"
"    'expected_result': [\n"
"        'BO record created in Onboarding Microservice and synced to Salesforce FSC within 30s. Account proceeds to next onboarding step.',\n"
"        'Two BO records created. Both accepted as valid 25% threshold. Account proceeds.',\n"
"        'System rejects submission with mandatory field error. Account status remains pending. No activation.',\n"
"        'No PEP matches returned. Screening result stored. Application proceeds to next step.',\n"
"        'Fallback procedure triggered. Diana alerted. Manual PEP screening initiated. Account proceeds with documented manual check.',\n"
"        'PEP match confirmed. Account flagged High Risk. Sarah Chen alerted. Onboarding paused. Manual review required before proceeding.',\n"
"        'Verification evidence stored with pass result. ID verification marked complete.',\n"
"        'Manual review initiated. Operations notified. Review completed within 48 hours. Result stored.',\n"
"        'Fallback triggered. Operations alerted within 5 minutes. Manual ID check completed within 24 hours.',\n"
"        'Audit log entry confirmed in both Audit DB and Salesforce FSC within 60 seconds of submission.',\n"
"        'Retry mechanism activates. Operations alerted after 3 failed retries. Audit data not lost. Sync completes automatically when service restored.',\n"
"        'Hash matches. Record has not been altered since creation. Immutable audit trail confirmed.',\n"
"        'Risk rating of Medium assigned. Correct rating applied based on scoring rules.',\n"
"        'High Risk rating applied. Correct escalation to Compliance Review.',\n"
"        'Default Medium Risk rating applied. Client notified. Data completion workflow initiated. Risk score updated once data provided.'\n"
"    ],\n"
"    'pass_fail_criteria': [\n"
"        'BO record exists in both systems with correct data within 30 seconds',\n"
"        'Both records stored with correct 25% ownership designation',\n"
"        'System blocks activation. Error displayed. No data committed without all mandatory fields.',\n"
"        'API call made. Result stored. No errors. Proceed.',\n"
"        'Alert sent within 5 min. Manual process initiated. SLA met.',\n"
"        'Account flagged. Email sent. Onboarding paused. Manual review completed.',\n"
"        'Evidence stored with correct result and timestamp.',\n"
"        'Manual review completed within 48h. Result stored and client notified.',\n"
"        'Fallback initiated. Manual process completed within 24h. No data lost.',\n"
"        'Entry confirmed in both systems within 60 seconds.',\n"
"        'No data lost. Auto-retry works. Operations alerted appropriately.',\n"
"        'Hash verified. No tampering. Integrity confirmed.',\n"
"        'Correct score computed. Correct rating assigned.',\n"
"        'High Risk applied. Escalation triggered.',\n"
"        'Default rating applied. Client notified. Data workflow initiated.'\n"
"    ],\n"
"    'cross_system': ['No','No','No',\n"
"                     'Yes - Dow Jones API','Yes - Dow Jones API','Yes - Dow Jones API',\n"
"                     'Yes - Experian API','Yes - Experian API','Yes - Experian API',\n"
"                     'Yes - Salesforce FSC','Yes - Salesforce FSC','No',\n"
"                     'No','No','No']\n"
"}\n"
"\n"
"df_scenarios = pd.DataFrame(scenarios)\n"
"print('Total test scenarios:', len(df_scenarios))\n"
"print()\n"
"df_scenarios[['ts_id','req_id','scenario_type','title']]\n"
))

cells4.append(nbf.v4.new_markdown_cell("## 4. Cross-System Failure Scenarios\n"))

cells4.append(nbf.v4.new_code_cell(
"# CROSS-SYSTEM SCENARIOS - from Prompt 4.2\n"
"\n"
"cross_system = {\n"
"    'cs_id': ['CS-001','CS-002','CS-003','CS-004','CS-005'],\n"
"    'scenario': [\n"
"        'Experian API Unavailable During ID Verification',\n"
"        'Salesforce FSC Unreachable During BO Record Sync',\n"
"        'Dow Jones API Returns PEP Match',\n"
"        'Audit Log Database Connection Timeout',\n"
"        'BO Declaration Submitted with SQL Injection Attempt'\n"
"    ],\n"
"    'systems_affected': [\n"
"        'Web App -> Onboarding Microservice -> Experian API',\n"
"        'Onboarding Microservice -> Salesforce FSC',\n"
"        'Onboarding Microservice -> Dow Jones API -> Salesforce FSC',\n"
"        'Onboarding Microservice -> Audit DB',\n"
"        'Web App -> Onboarding Microservice'\n"
"    ],\n"
"    'failure_detection': [\n"
"        'Onboarding Microservice receives HTTP 503 from Experian after 30s timeout',\n"
"        'Onboarding Microservice connection to Salesforce FSC times out after 10s',\n"
"        'Dow Jones API returns PEP match with confidence score > 0.85',\n"
"        'Audit DB connection pool exhausted; new connections rejected',\n"
"        'Input validation in Microservice detects SQL injection pattern in BO name field'\n"
"    ],\n"
"    'expected_behaviour': [\n"
"        'System retries once. Second failure triggers Operations alert within 5 min. Manual ID check fallback activated. Client informed of slight delay.',\n"
"        'Onboarding Microservice retries 3 times with exponential backoff. After 3 failures, record held locally with sync flag. Operations alerted. Sync completes when Salesforce FSC available. No data loss.',\n"
"        'System immediately flags account as High Risk. Account moved to Compliance Review queue. Email alert to Sarah Chen within 5 minutes. Diana notified for manual Dow Jones review. Account cannot progress until manual clearance received.',\n"
"        'Onboarding Microservice logs audit entry locally first (write-ahead log). Retry connection to Audit DB. If Audit DB unavailable after 3 retries, alert Operations. Data preserved locally. No audit entry lost.',\n"
"        'Input validation rejects submission. Error displayed to client: "Invalid characters in field." No data written to database. No injection possible. Security alert logged.'\n"
"    ],\n"
"    'test_data_required': [\n"
"        'Simulated HTTP 503 from Experian API (use API mocking tool or sandbox)',\n"
"        'Salesforce FSC unavailable (use separate test environment or Salesforce sandbox)',\n"
"        'Test data: known PEP individual in Dow Jones sandbox environment',\n"
"        'Simulate Audit DB connection failure (use database-level constraints)',\n"
"        'Test payloads: \"Robert'); DROP TABLE clients;--\" and \"<script>alert(1)</script>\"'\n"
"    ]\n"
"}\n"
"\n"
"df_cs = pd.DataFrame(cross_system)\n"
"print('Cross-System Failure Scenarios:', len(df_cs))\n"
"df_cs[['cs_id','scenario','systems_affected']]\n"
))

cells4.append(nbf.v4.new_markdown_cell("## 5. Traceability Matrix\n"))

cells4.append(nbf.v4.new_code_cell(
"# REQUIREMENTS TO TEST SCENARIOS TRACEABILITY MATRIX\n"
"\n"
"print('TRACEABILITY MATRIX - Sprint 1')\n"
"print('='*65)\n"
"\n"
"for req_id in df_scenarios['req_id'].unique():\n"
"    scenarios_for_req = df_scenarios[df_scenarios['req_id']==req_id]\n"
"    happy = len(scenarios_for_req[scenarios_for_req['scenario_type']=='Happy Path'])\n"
"    alt = len(scenarios_for_req[scenarios_for_req['scenario_type']=='Alternative Path'])\n"
"    fail = len(scenarios_for_req[scenarios_for_req['scenario_type']=='Failure Path'])\n"
"    cross = len(scenarios_for_req[scenarios_for_req['cross_system']=='Yes'])\n"
"    print(f'{req_id}: {len(scenarios_for_req)} scenarios (Happy={happy}, Alt={alt}, Fail={fail}, CrossSystem={cross})')\n"
"\n"
"print()\n"
"# Check coverage\n"
"all_reqs = set(df_fr['req_id'].tolist())\n"
"tested_reqs = set(df_scenarios['req_id'].unique())\n"
"missing = all_reqs - tested_reqs\n"
"if missing:\n"
"    print('WARNING - Requirements with NO test scenarios:', missing)\n"
"else:\n"
"    print('All Sprint 1 requirements have test scenario coverage.')\n"
))

cells4.append(nbf.v4.new_markdown_cell("## 6. Export\n"))

cells4.append(nbf.v4.new_code_cell(
"df_scenarios.to_csv('../outputs/test_scenario_register.csv', index=False)\n"
"df_cs.to_csv('../outputs/cross_system_scenarios.csv', index=False)\n"
"\n"
"print('Exported:')\n"
"for f in ['test_scenario_register.csv','cross_system_scenarios.csv']:\n"
"    print('  -', f)\n"
))

cells4.append(nbf.v4.new_markdown_cell(
"## AI Prompt Library - Task 4\n"
"\n"
"### Prompt 4.1: Test Scenario from Acceptance Criteria\n"
"\n"
"```\n"
"Generate happy, alternative, and failure path test scenarios from this acceptance criterion:\n"
"[paste acceptance criterion]\n"
"\n"
"For each scenario: Given [precondition] when [action] then [observable result].\n"
"Also: what would FAIL this test, what could go WRONG mid-scenario, and test data needed.\n"
"```\n"
"\n"
"### Prompt 4.2: Cross-System Failure Scenarios\n"
"\n"
"```\n"
"Systems: Web App (React), Onboarding Microservice (Node.js/PostgreSQL),\n"
"Salesforce FSC, Experian Verify API, Dow Jones Risk Intel API, Audit DB.\n"
"\n"
"For each failure: what each system detects, expected behaviour, test scenario outline, test data.\n"
"\n"
"Failures:\n"
"A. Experian API HTTP 503 during ID verification\n"
"B. Dow Jones returns PEP true positive\n"
"C. Salesforce FSC unreachable during BO sync\n"
"D. Audit DB connection timeout\n"
"E. BO declaration with SQL injection\n"
"```\n"
"\n"
"### Prompt 4.3: Edge Case Discovery\n"
"\n"
"```\n"
"Review these test scenarios and identify:\n"
"- Edge cases NOT covered\n"
"- Hidden assumptions in preconditions\n"
"- Data validation gaps\n"
"- Concurrency scenarios\n"
"- Regulatory edge cases\n"
"\n"
"[paste scenarios]\n"
"```\n"
))

nb4.cells = cells4
with open('/opt/data/capstone/notebooks/Task_4_UAT_Testing.ipynb', 'w') as f:
    nbf.write(nb4, f)
print("Task 4 notebook written")

# ─────────────────────────────────────────────────────────────────────────────
# TASK 5 NOTEBOOK
# ─────────────────────────────────────────────────────────────────────────────
nb5 = nbf.v4.new_notebook()
nb5.metadata = {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}}

cells5 = []

cells5.append(nbf.v4.new_markdown_cell(
"# Task 5 - Executive Presentation and Regulatory Submission\n"
"## AI-Augmented Business Analyst Capstone\n"
"**Company:** Meridian Financial | **Scenario:** FCA KYC/AML Onboarding Remediation\n"
"---\n"
"## Overview\n"
"You have received the email from Sarah Chen. The 6-week FCA deadline is approaching. You must produce:\n"
"1. A **2-3 page Executive Summary** for Marcus Reid (CFO)\n"
"2. A **10-slide presentation deck** for the FCA Supervision team\n"
"3. A **Q&A Preparation Brief** for the stakeholder rehearsal\n"
"4. A **Draft Regulatory Submission Document** for Priya Sharma (Legal) review\n"
"\n"
"This task synthesises all prior deliverables into a coherent narrative.\n"
"\n"
"## Key Dates\n"
"- Today: [Current Date]\n"
"- Sprint 1 End: +10 weeks\n"
"- FCA 90-Day Deadline: +12 weeks\n"
"- Presentation to FCA: +12 weeks\n"
"---\n"
))

cells5.append(nbf.v4.new_markdown_cell("## 1. Load All Prior Outputs\n"))
cells5.append(nbf.v4.new_code_cell(
"import pandas as pd\n"
"import matplotlib.pyplot as plt\n"
"import os\n"
"os.makedirs('../outputs', exist_ok=True)\n"
"\n"
"df_gaps = pd.read_csv('../outputs/regulatory_gap_analysis.csv')\n"
"df_fr = pd.read_csv('../outputs/functional_requirements.csv')\n"
"df_nfr = pd.read_csv('../outputs/non_functional_requirements.csv')\n"
"df_backlog = pd.read_csv('../outputs/requirements_backlog.csv')\n"
"df_int_gaps = pd.read_csv('../outputs/integration_gap_analysis.csv')\n"
"df_scenarios = pd.read_csv('../outputs/test_scenario_register.csv')\n"
"\n"
"print('Gaps:', len(df_gaps))\n"
"print('Functional requirements:', len(df_fr))\n"
"print('Non-functional requirements:', len(df_nfr))\n"
"print('Integration gaps:', len(df_int_gaps))\n"
"print('Test scenarios:', len(df_scenarios))\n"
"\n"
"high_gaps = df_gaps[df_gaps['severity']=='High']\n"
"print()\n"
"print('HIGH SEVERITY GAPS:', len(high_gaps))\n"
"for _, g in high_gaps.iterrows():\n"
"    print(' -', g['gap_id'], '-', g['gap_name'])\n"
))

cells5.append(nbf.v4.new_markdown_cell(
"## 2. Executive Summary - Draft\n"
"\n"
"> **Activity:** Review the AI-generated executive summary below. Edit it to ensure:\n"
"> - Marcus Reid can understand it in 3 minutes\n"
"> - No unexplained acronyms or BA jargon\n"
"> - Consequences of inaction are specific (not vague)\n"
"> - The ask is clear\n"
"\n"
"Use **Prompt 5.1** to generate a first draft.\n"
))

cells5.append(nbf.v4.new_code_cell(
"executive_summary = '''\n"
"EXECUTIVE SUMMARY - FOR INTERNAL USE / FCA SUBMISSION DRAFT\n"
"Meridian Financial - KYC/AML Onboarding Remediation\n"
"Prepared by: Business Analysis Team\n"
"Date: [Current Date]\n"
"\n"
"THE PROBLEM\n"
"-----------\n"
"The FCA has formally notified Meridian Financial (ref: FCA/ONB/2024/0471) of gaps in our\n"
"client onboarding process that relate to Know Your Customer (KYC) and Anti-Money Laundering\n"
"(AML) compliance controls. The FCA has given us 90 days to demonstrate a credible plan\n"
"to fix these gaps.\n"
"\n"
"Our discovery found [X] regulatory gaps across the onboarding process, ranging from missing\n"
"beneficial ownership collection to a complete absence of automated audit logging. The most\n"
"serious gaps expose Meridian to FCA enforcement action, including fines and, in a worst case,\n"
"withdrawal of regulatory authorisation.\n"
"\n"
"WHAT WE FOUND\n"
"-------------\n"
"The onboarding process - from initial inquiry to account activation - has [X] significant\n"
"gaps in its compliance controls. These include:\n"
"\n"
"- No automated identity verification: ID checks are done manually by email, with no system\n"
"  recording the outcome\n"
"- No beneficial ownership data collected: we do not currently meet the legal requirement to\n"
"  collect ownership information for legal entity clients (FCA MLR 2017 Reg 28)\n"
"- No automated PEP screening: Politically Exposed Person checks are run by hand when Diana\n"
"  remembers, with no automated trigger or audit trail\n"
"- No compliance-grade audit log: compliance sign-offs are conducted by email - not a\n"
"  compliant record for FCA purposes\n"
"- No automated sanctions screening: no screening against official sanctions lists is performed\n"
"  as part of onboarding\n"
"\n"
"WHAT WE ARE BUILDING\n"
"--------------------\n"
"We are rebuilding the onboarding process in two phases:\n"
"\n"
"Sprint 1 (10 weeks, starting [Date]): Fixes the highest-risk gaps. Delivers: mandatory\n"
"beneficial ownership declaration, automated PEP and sanctions screening, identity\n"
"verification evidence capture, automated compliance audit logging, and client risk rating\n"
"at application. Total estimated build cost: [GBP 80-120k]. Third-party tooling costs:\n"
"[GBP 15-25k/year].\n"
"\n"
"Sprint 2 (TBD): Addresses remaining medium-priority gaps including full FCA reporting\n"
"capability and enhanced monitoring.\n"
"\n"
"WHY A THIRD-PARTY VENDOR?\n"
"For beneficial ownership verification, we evaluated building in-house vs. buying. We are\n"
"recommending an integration with a specialist BO verification platform (Kyckr or Enumacloud)\n"
"because: (a) it can be integrated in 1-2 weeks vs. 6-8 for building in-house, (b) it\n"
"provides automated coverage of Companies House data, and (c) the total cost is lower\n"
"than the engineering time to build this from scratch.\n"
"\n"
"WHY 10 WEEKS?\n"
"The Sprint 1 scope was designed to address every HIGH severity gap within the 90-day FCA\n"
"window. We have structured the sprint with 2-week buffer to absorb technical risks.\n"
"\n"
"RISK AND RESIDUAL RISK\n"
"----------------------\n"
"After Sprint 1, Meridian will have addressed all HIGH severity gaps. The following will\n"
"remain as residual risk:\n"
"\n"
"- Sprint 2 gaps (medium severity) will not be fully resolved\n"
"- Third-party vendor dependency for BO verification creates a vendor risk\n"
"- The existing Salesforce FSC and Microservice integration remains technically complex\n"
"\n"
"We will monitor all residual risks via the monthly Compliance Operations Review.\n"
"\n"
"CONSEQUENCES OF INACTION\n"
"------------------------\n"
"If we do not address these gaps within 90 days, the FCA can:\n"
"\n"
"- Issue a public censure or fine of up to GBP 250M or 10% of global annual turnover\n"
"- Require us to cease onboarding new clients until gaps are remedied\n"
"- In serious cases, initiate proceedings to withdraw our regulatory authorisation\n"
"\n"
"Behaviours of this severity have occurred at other firms. In 2023, the FCA fined a\n"
"comparable fintech GBP 1.8M for AML control failures in its onboarding process.\n"
"\n"
"RECOMMENDED ACTIONS\n"
"------------------\n"
"1. Marcus Reid (CFO) approves Sprint 1 budget by [Date + 1 week]\n"
"2. Sarah Chen (Compliance) confirms vendor selection for BO verification by [Date + 2 weeks]\n"
"3. James Okafor (Product) briefs Diana Vlasova (Engineering) for sprint kick-off on [Date]\n"
"4. Sarah Chen submits interim update to FCA Supervisor by [Date + 4 weeks] confirming plan\n"
"5. All parties commit to weekly sprint reviews for duration of Sprint 1\n"
"'''\n"
"\n"
"print(executive_summary)\n"
))

cells5.append(nbf.v4.new_markdown_cell("## 3. Presentation Deck - Slide Scaffolding\n"))

cells5.append(nbf.v4.new_code_cell(
"# SLIDE OUTLINES - complete with your content\n"
"\n"
"slides = {\n"
"    1: {'title':'Agenda','key_message':'Clear, honest overview of what we will present',\n"
"        'content':['Background and context','What we found','What we are building','Timeline and cost','Risk and governance'],\n"
"        'speaker_notes':'Set the tone: this is an honest account. We found problems, we are fixing them.'},\n"
"\n"
"    2: {'title':'Background - Meridian Financial',\n"
"        'key_message':'Meridian is a UK FCA-regulated fintech serving SME payroll and contractor payments',\n"
"        'content':['250 employees, Series B, open banking payments platform','FCA-regulated for payment services and anti-money laundering','c. GBP 40M ARR, c. 500 active SME clients','In 2024, FCA Supervision opened a review of our onboarding KYC/AML controls'],\n"
"        'speaker_notes':'Establish credibility quickly. The FCA knows who we are - focus on our response.'},\n"
"\n"
"    3: {'title':'What We Found',\n"
"        'key_message':'Discovery identified 7 regulatory gaps in our onboarding process',\n"
"        'content':['7 gaps identified across 9 onboarding steps','4 rated HIGH severity (regulatory enforcement risk)','3 rated MEDIUM severity','Top issues: BO collection absent, PEP screening manual, no audit trail'],\n"
"        'speaker_notes':'Be factual. This is not about blame - it is about identifying what needs fixing.'},\n"
"\n"
"    4: {'title':'The Gaps - Regulatory References',\n"
"        'key_message':'Gaps mapped to specific FCA regulatory requirements - we know exactly what is required',\n"
"        'content':['G-001: FCA PS17/4 S.4.2 - identity verification adequacy','G-002: FCA MLR 2017 Reg 28 - beneficial ownership (CRIMINAL liability)','G-003: FCA MLR 2017 Reg 35 - PEP screening','G-004: FCA PS17/14 S.6 - audit trail and record keeping'],\n"
"        'speaker_notes':'The FCA reviewers know these regulations. Do not explain what a PEP is. Be precise.'},\n"
"\n"
"    5: {'title':'Our Proposed Solution - Sprint 1',\n"
"        'key_message':'We will fix all HIGH severity gaps within the 90-day window',\n"
"        'content':['5 functional requirements: BO declaration, automated PEP screening, ID evidence capture, audit log, risk rating','3 NFRs: 5-year audit retention, API response SLA, WCAG accessibility','New integrations: Companies House API, Dow Jones API automation','In-sprint buffer: 2 weeks built in for technical risk'],\n"
"        'speaker_notes':'The FCA wants to know we have a credible plan. Be specific about what we are delivering.'},\n"
"\n"
"    6: {'title':'Solution Architecture',\n"
"        'key_message':'We are building on existing systems with targeted new integrations',\n"
"        'content':['Core: Salesforce FSC + custom Onboarding Microservice (existing)','New: BO declaration form + Companies House API integration','New: Automated Dow Jones API for PEP/sanctions screening','New: Compliance-grade audit log database','Third-party vendors: Kyckr or Enumacloud for BO verification'],\n"
"        'speaker_notes':'Simplify for the FCA audience. Focus on the new pieces, not the full technical diagram.'},\n"
"\n"
"    7: {'title':'Vendor Decisions',\n"
"        'key_message':'We selected specialist third-party tools where building in-house would take too long',\n"
"        'content':['BO verification: build in-house = 6-8 weeks; vendor integration = 1-2 weeks. We chose to integrate.','Vendor evaluation criteria: FCA compliance history, UK market presence, data residency','All vendors required to sign data processing agreements (UK GDPR)'],\n"
"        'speaker_notes':'The FCA may ask why we chose vendors. Have this answer ready: speed, compliance expertise, cost.'},\n"
"\n"
"    8: {'title':'Timeline and Milestones',\n"
"        'key_message':'We are on track to deliver within the 90-day window',\n"
"        'content':['Sprint 1 Kick-off: [Date]','Build complete: [Date + 8 weeks]','UAT: [Date + 8-10 weeks]','FCA 90-day deadline: [Date + 12 weeks]','2-week buffer in sprint protects against technical risk'],\n"
"        'speaker_notes':'Show the timeline visually. Be honest: what could blow it? (Answer: Salesforce FSC sync complexity)'},\n"
"\n"
"    9: {'title':'Cost',\n"
"        'key_message':'Sprint 1 investment: one-off build cost plus ongoing tooling subscription',\n"
"        'content':['Engineering build cost: GBP 80-120k (3 engineers x 10 weeks)','Third-party tooling: GBP 15-25k/year (API subscriptions)','Ongoing compliance cost: minimal - no new headcount required','Sprint 2 (deferred): estimated GBP 40-60k additional build'],\n"
"        'speaker_notes':'Marcus will scrutinise these numbers. Be ready to justify T-shirt sizing estimates.'},\n"
"\n"
"    10: {'title':'Risk and Residual Risk',\n"
"        'key_message':'After Sprint 1, all HIGH severity gaps are addressed. Medium gaps remain with a monitoring plan.',\n"
"        'content':['All HIGH severity gaps: addressed by Sprint 1 delivery','Sprint 2 gaps (medium): will not be fully resolved - monitoring plan in place','Vendor dependency: fallback manual procedures defined for all third-party integrations','Integration complexity: Salesforce FSC sync is highest technical risk - 2-week buffer built in'],\n"
"        'speaker_notes':'Be honest. The FCA will find out if we are overstating our position.'},\n"
"\n"
"    11: {'title':'Governance and Prevention',\n"
"        'key_message':'We have put in place a governance structure to ensure this does not happen again',\n"
"        'content':['Monthly Compliance Operations Review: ongoing monitoring of onboarding controls','Quarterly BA reviews of onboarding process against FCA regulatory changes','Annual regulatory training for all staff involved in onboarding','FCA regulatory horizon-scanning added to Compliance team objectives'],\n"
"        'speaker_notes':'This is what the FCA most wants to hear: what are you doing to prevent recurrence?'},\n"
"\n"
"    12: {'title':'What We Are Asking of the FCA',\n"
"        'key_message':'We need the FCA to note our remediation plan and confirm no further immediate action',\n"
"        'content':['Meridian commits to delivering Sprint 1 by [Date + 10 weeks]','Meridian will provide a written progress update at 6 weeks','Meridian requests confirmation that the FCA accepts this remediation timeline','Any additional guidance from the FCA on interpretation of MLR 2017 Reg 28 would be welcome'],\n"
"        'speaker_notes':'Make the ask clear and modest. Do not ask for anything you are not entitled to ask for.'}\n"
"}\n"
"\n"
"for slide_num, slide in slides.items():\n"
"    print(f'--- SLIDE {slide_num}: {slide[\"title\"]} ---')\n"
"    print(f'Key message: {slide[\"key_message\"]}')\n"
"    print('Content:', ', '.join(slide['content']))\n"
"    print()\n"
))

cells5.append(nbf.v4.new_markdown_cell("## 4. Q&A Preparation Brief\n"))

cells5.append(nbf.v4.new_code_cell(
"# DIFFICULT QUESTIONS AND PREPARED ANSWERS\n"
"\n"
"qa_brief = '''\n"
"Q&A PREPARATION BRIEF - Task 5\n"
"================================\n"
"\n"
"Q1: Marcus Reid (CFO) - \"How do you know Salesforce FSC can actually do this?\"\n"
"-----------------------------------------------------------------------\n"
"WHY IT IS DIFFICULT: Diana flagged this as unvalidated. We have assumed Salesforce FSC\n"
"can store BO records and sync with the Microservice, but we have not tested this.\n"
"\n"
"PREPARED ANSWER:\n"
"We have identified the Salesforce FSC sync as the highest technical risk in Sprint 1.\n"
"Engineering will validate this assumption in the first two weeks of Sprint 1 (discovery\n"
"sprint). If Salesforce FSC cannot support the required data model, we have two fallback\n"
"options: (a) store BO records primarily in the Microservice with a read-only sync to\n"
"Salesforce FSC, or (b) evaluate a custom object in Salesforce FSC. We will provide Marcus\n"
"with an update on this at the Week 2 sprint review.\n"
"\n"
"WHAT NOT TO SAY: \"We are confident Salesforce can handle it.\" Diana has not validated this.\n"
"\n"
"---\n"
"\n"
"Q2: Sarah Chen (Compliance) - \"Is this actually compliant or just more compliant?\"\n"
"---------------------------------------------------------------------------\n"
"WHY IT IS DIFFICULT: We cannot eliminate all AML risk. There will always be residual risk.\n"
"\n"
"PREPARED ANSWER:\n"
"After Sprint 1, Meridian will meet the minimum standards required by FCA PS17/14 and\n"
"MLR 2017 for the onboarding process. We will not have eliminated all AML risk - that is\n"
"not achievable without infinite engineering resource. What we will have is a documented,\n"
"automated, auditable process that meets the regulatory threshold. Medium-severity gaps\n"
"remain and we have a plan to address them in Sprint 2. Sarah, I would like to walk\n"
"through the residual risk register with you separately.\n"
"\n"
"WHAT NOT TO SAY: \"We are fully compliant.\" - This is not credible and the FCA will know it.\n"
"\n"
"---\n"
"\n"
"Q3: Diana Vlasova (Engineering) - \"That Salesforce FSC sync is a 3-month problem. How does it fit in 10 weeks?\"\n"
"-----------------------------------------------------------------------------------------------\n"
"WHY IT IS DIFFICULT: She is right. This is a genuine technical risk.\n"
"\n"
"PREPARED ANSWER:\n"
"You are right that a full bidirectional sync between a legacy Microservice and Salesforce\n"
"FSC is typically a 3-month problem. Our approach in Sprint 1 is intentionally narrower:\n"
"we are building a unidirectional sync (Microservice -> Salesforce FSC) for the compliance\n"
"audit data, which is technically simpler. The bidirectional sync for account data is\n"
"deferred to Sprint 2. We have also built in a 2-week buffer specifically to absorb this\n"
"risk. If at Week 4 it is clear the sync cannot be delivered in Sprint 1, we will\n"
"escalate immediately to James and Sarah to descope or extend.\n"
"\n"
"---\n"
"\n"
"Q4: Priya Sharma (Legal) - \"What is our residual AML risk after Sprint 1?\"\n"
"-----------------------------------------------------------------------\n"
"WHY IT IS DIFFICULT: You cannot eliminate all AML risk.\n"
"\n"
"PREPARED ANSWER:\n"
"After Sprint 1, our residual AML risk is: (1) clients who onboard during Sprint 2 will\n"
"not benefit from enhanced monitoring until Sprint 2 is complete; (2) we will have a\n"
"monitored fallback procedure for third-party API failures which introduces a small\n"
"manual-error risk; (3) our financial crime transaction monitoring post-onboarding is\n"
"out of scope for Sprint 1. I would recommend Legal and Compliance review the residual\n"
"risk register before the FCA meeting and formally sign off on what is acceptable.\n"
"\n"
"---\n"
"\n"
"Q5: James Okafor (Product) - \"Why a third-party vendor for BO verification? I thought we did not want lock-in.\n"
"-----------------------------------------------------------------------------------------------\n"
"WHY IT IS DIFFICULT: He has a valid concern about vendor lock-in.\n"
"\n"
"PREPARED ANSWER:\n"
"The concern about lock-in is valid for our core platform decisions. For BO verification,\n"
"the calculus is different: the regulatory requirement is to verify BO information against\n"
"Companies House - a government API. The specialist platforms (Kyckr, Enumacloud) provide\n"
"an abstraction layer over this API plus additional data sources, but the underlying\n"
"obligation is the same. Vendor lock-in risk is mitigated by: (a) keeping the BO record\n"
"in our own Microservice database, not in the vendor system, (b) using standard API\n"
"integration patterns that allow vendor replacement, and (c) requiring 90-day notice\n"
"clauses in all vendor contracts.\n"
"\n"
"WHAT NOT TO SAY: \"It is only GBP 15k/year so it does not matter.\" - This dismisses a valid concern.\n"
"'''\n"
"\n"
"print(qa_brief)\n"
))

cells5.append(nbf.v4.new_markdown_cell("## 5. Export Final Deliverables\n"))

cells5.append(nbf.v4.new_code_cell(
"# Save executive summary\n"
"with open('../outputs/executive_summary.txt','w') as f:\n"
"    f.write(executive_summary)\n"
"\n"
"# Save slide scaffolding\n"
"import json\n"
"with open('../outputs/slide_scaffolding.json','w') as f:\n"
"    # Convert slide numbers to strings for JSON\n"
"    json_slides = {str(k): v for k, v in slides.items()}\n"
"    json.dump(json_slides, f, indent=2)\n"
"\n"
"# Save Q&A brief\n"
"with open('../outputs/qa_preparation_brief.txt','w') as f:\n"
"    f.write(qa_brief)\n"
"\n"
"print('Exported:')\n"
"for f in ['executive_summary.txt','slide_scaffolding.json','qa_preparation_brief.txt']:\n"
"    print('  -', f)\n"
"\n"
"print()\n"
"print('='*60)\n"
"print('CAPSTONE PROGRAMME - ALL OUTPUTS EXPORTED')\n"
"print('='*60)\n"
"print()\n"
"import os\n"
"for root, dirs, files in os.walk('../outputs'):\n"
"    for f in files:\n"
"        path = os.path.join(root, f)\n"
"        size = os.path.getsize(path)\n"
"        print(f'  {path} ({size} bytes)')\n"
))

cells5.append(nbf.v4.new_markdown_cell(
"## AI Prompt Library - Task 5\n"
"\n"
"### Prompt 5.1: Executive Summary Generation\n"
"\n"
"```\n"
"Write a 2-3 page executive summary for a CFO of a UK fintech facing an FCA regulatory notice.\n"
"\n"
"Context:\n"
"- Meridian Financial: GBP 40M ARR, 250 employees, FCA-regulated fintech\n"
"- FCA notice: KYC/AML onboarding gaps, 90-day deadline\n"
"- Discovery complete: 7 gaps (4 high, 3 medium)\n"
"- Sprint 1 (10 weeks): fixes all high gaps\n"
"- Cost: GBP 80-120k build + GBP 15-25k/year tooling\n"
"\n"
"Write for a numerate, risk-aware CFO. No jargon. No unexplained acronyms.\n"
"Consequences of inaction must be specific and credible.\n"
"```\n"
"\n"
"### Prompt 5.2: Slide Scaffolding\n"
"\n"
"```\n"
"Create slide outlines for an FCA regulatory submission presentation:\n"
"\n"
"Slides: Agenda, Background, What We Found, The Gaps, Proposed Solution,\n"
"Solution Architecture, Vendor Decisions, Timeline, Cost, Risk and Residual Risk,\n"
"Governance and Prevention, Recommended Actions.\n"
"\n"
"For each slide: key message, content bullets, data viz recommendation,\n"
"speaker notes (60 seconds max), and anticipated questions.\n"
"\n"
"Audience: FCA Compliance supervisors, Meridian CFO, Head of Compliance, Legal Counsel.\n"
"```\n"
"\n"
"### Prompt 5.3: Q&A Preparation\n"
"\n"
"```\n"
"Prepare for a hostile Q&A with a CFO, Compliance Lead, Product Manager,\n"
"Lead Engineer, and Legal Counsel on a UK fintech FCA remediation project.\n"
"\n"
"For each difficult question:\n"
"- Why it is difficult\n"
"- What the questioner needs to hear\n"
"- The honest answer\n"
"- The dangerous answer (what NOT to say)\n"
"- The prepared answer\n"
"\n"
"Questions: Salesforce FSC capability, vendor lock-in, residual AML risk,\n"
"timeline credibility, and consequences of inaction.\n"
"```\n"
))

nb5.cells = cells5
with open('/opt/data/capstone/notebooks/Task_5_Presentation.ipynb', 'w') as f:
    nbf.write(nb5, f)
print("Task 5 notebook written")
print()
print("ALL TASKS COMPLETE")
