"""
Build script for Task 2 notebook - Requirements Engineering
"""
import nbformat as nbf

nb = nbf.v4.new_notebook()
nb.metadata = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.10.0"}
}

cells = []

cells.append(nbf.v4.new_markdown_cell(
"# Task 2 - Requirements Engineering\n"
"## AI-Augmented Business Analyst Capstone\n"
"**Company:** Meridian Financial | **Scenario:** FCA KYC/AML Onboarding Remediation\n"
"**Task 1 Inputs Required:** `stakeholder_register.csv`, `regulatory_gap_analysis.csv`\n"
"---\n"
"## Overview\n"
"You have received the email from James Okafor (Product Manager). Your task is to convert the gap analysis from Task 1 into a full requirements package.\n"
"By the end of this notebook you will have produced:\n"
"1. A **Functional Requirements package** (FR-001 onwards) with acceptance criteria\n"
"2. A **Non-Functional Requirements package** (NFR-001 onwards)\n"
"3. A **Requirements Backlog** prioritised using MoSCoW\n"
"4. A **Requirements Review Notes** document (self-review before Engineering)\n"
"---\n"
))

cells.append(nbf.v4.new_markdown_cell("## 1. Load Task 1 Outputs\n"))
cells.append(nbf.v4.new_code_cell(
"import pandas as pd\n"
"import os\n"
"os.makedirs('../outputs', exist_ok=True)\n"
"\n"
"df_gaps = pd.read_csv('../outputs/regulatory_gap_analysis.csv')\n"
"df_process = pd.read_csv('../outputs/as_is_process_map.csv')\n"
"\n"
"print('Loaded gaps:', len(df_gaps))\n"
"print('Loaded process steps:', len(df_process))\n"
"print()\n"
"print('HIGH SEVERITY GAPS:')\n"
"print(df_gaps[df_gaps['severity']=='High'][['gap_id','gap_name']].to_string(index=False))\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 2. Functional Requirements\n"
"\n"
"### Framework\n"
"- **Req ID** - FR-001, FR-002, etc.\n"
"- **Description** - What the system MUST do (specific, measurable)\n"
"- **Source Gap** - Maps to gap ID from Task 1\n"
"- **Regulatory Reference** - FCA PS17/14 or MLR 2017 citation\n"
"- **Priority** - MoSCoW: Must / Should / Could / Won't\n"
"- **Acceptance Criteria** - Given/When/Then format, minimum 3 per requirement\n"
"\n"
"> **Activity:** Complete the requirements table below. Use Prompt 2.1 to generate drafts, then refine.\n"
))

cells.append(nbf.v4.new_code_cell(
"# COMPLETE THIS TABLE - one row per requirement\n"
"\n"
"fr_data = {\n"
"    'req_id': ['FR-001','FR-002','FR-003','FR-004','FR-005'],\n"
"    'title': [\n"
"        'Mandatory Beneficial Ownership Declaration',\n"
"        'Automated PEP and Sanctions Screening',\n"
"        'Identity Verification Evidence Capture',\n"
"        'Automated Compliance Audit Log',\n"
"        'Client Risk Rating at Application Submission'\n"
"    ],\n"
"    'source_gap': ['G-002','G-003','G-001','G-004','G-005'],\n"
"    'regulatory_reference': [\n"
"        'FCA MLR 2017 Reg 28',\n"
"        'FCA MLR 2017 Reg 35; FCA PS17/14 S.4',\n"
"        'FCA PS17/14 S.4.2 (CDD adequacy)',\n"
"        'FCA PS17/14 S.6 (audit trail)',\n"
"        'FCA PS17/14 S.4 (risk assessment)'\n"
"    ],\n"
"    'priority': ['Must Have','Must Have','Must Have','Must Have','Should Have'],\n"
"    'description': [\n"
"        'The system MUST require a completed beneficial ownership declaration from all legal entity clients before account activation. The declaration MUST capture: full name, date of birth, nationality, residential address, ownership percentage, and role for each individual owning or controlling 25% or more of the client entity.',\n"
"        'The system MUST automatically execute a PEP and sanctions screening check via the Dow Jones Risk Intelligence API for all named individuals in the account application and beneficial ownership declaration, at the point of submission.',\n"
"        'The system MUST capture and store evidence of identity verification including: document type, document reference number, verification result (pass/fail/refer), and verification timestamp, in a compliance-grade audit record.',\n"
"        'The system MUST create an automated, immutable audit log entry for every onboarding step, capturing: timestamp, actor (system or user ID), action performed, outcome, and supporting evidence reference.',\n"
"        'The system MUST assign a client risk rating (Low / Medium / High) automatically at account application submission, based on pre-defined rules including: country of operation, client entity type, BO nationality, PEP/sanctions match result, and ID verification result.'\n"
"    ],\n"
"    'dependencies': [\n"
"        'None - build first',\n"
"        'FR-001 (BO data required for screening)',\n"
"        'FR-001',\n"
"        'None',\n"
"        'FR-002 (risk score depends on screening)'\n"
"    ],\n"
"    'constraints': [\n"
"        'Must integrate with Companies House API for entity verification',\n"
"        'Must handle Dow Jones API errors gracefully with manual fallback',\n"
"        'Must store verification evidence in compliance-grade storage',\n"
"        'Audit log must be immutable once written',\n"
"        'Risk scoring rules must be configurable by Compliance without engineering'\n"
"    ]\n"
"}\n"
"\n"
"df_fr = pd.DataFrame(fr_data)\n"
"print('Functional requirements:', len(df_fr))\n"
"df_fr[['req_id','title','priority']]\n"
))

cells.append(nbf.v4.new_markdown_cell("## 3. Non-Functional Requirements\n"))

cells.append(nbf.v4.new_code_cell(
"nfr_data = {\n"
"    'req_id': ['NFR-001','NFR-002','NFR-003','NFR-004','NFR-005','NFR-006'],\n"
"    'category': ['Compliance','Performance','Security','Availability','Usability','Scalability'],\n"
"    'title': [\n"
"        'Audit Log Retention - 5 Years Minimum',\n"
"        'API Response Time - KYC Verification <= 30 Seconds',\n"
"        'Data Encryption - In Transit and at Rest',\n"
"        'System Uptime SLA - 99.5% During Business Hours',\n"
"        'WCAG 2.1 AA Accessibility Compliance',\n"
"        'Onboarding Volume - Scale to 100 Concurrent Sessions'\n"
"    ],\n"
"    'requirement': [\n"
"        'All compliance audit log records MUST be retained for a minimum of 5 years from the date of record, in a format that can be produced to the FCA within 24 hours of a regulatory request.',\n"
"        'The identity verification API call to Experian Verify MUST complete and return a result within 30 seconds under normal operating conditions. If no result is received within 30 seconds, the system MUST initiate a defined timeout procedure.',\n"
"        'All client PII and compliance data MUST be encrypted in transit (TLS 1.2 minimum) and at rest (AES-256 minimum). Encryption keys MUST be managed via a secrets management system.',\n"
"        'The onboarding system MUST maintain 99.5% uptime during UK business hours (07:00-19:00 Mon-Fri). Planned maintenance MUST be scheduled outside these hours with 5 days advance notice to Compliance.',\n"
"        'The onboarding portal MUST meet WCAG 2.1 AA accessibility standard, ensuring clients with disabilities can complete onboarding without assistance.',\n"
"        'The system architecture MUST support a minimum of 100 concurrent onboarding sessions without degradation of response times below the thresholds in NFR-002.'\n"
"    ],\n"
"    'measurement': [\n"
"        'FCA spot-check: audit log produced within 24 hours. Quarterly internal audit confirms all required fields present.',\n"
"        'Measured via API monitoring: p95 response time across 30-day period. Alert triggered if p95 > 25 seconds.',\n"
"        'Annual penetration test confirms no unencrypted PII. Evidence of secrets management configuration review.',\n"
"        'Uptime monitoring via synthetic monitoring tool. Monthly uptime report reviewed by Operations. SLA breach triggers incident review.',\n"
"        'Annual WCAG accessibility audit by certified third party. Critical and major issues remediated within 30 days.',\n"
"        'Load test quarterly: 100 concurrent sessions at peak-hour simulation. Metrics reviewed by Engineering Lead.'\n"
"    ],\n"
"    'regulatory_reference': [\n"
"        'FCA PS17/14 S.6 (record keeping); UK GDPR s.5(2)',\n"
"        'FCA Consumer Duty FG22/5',\n"
"        'UK GDPR Art. 32; FCA CLOUD 3',\n"
"        'FCA PS17/14 S.8',\n"
"        'Equality Act 2010; FCA Consumer Duty FG22/5',\n"
"        'FCA PS17/14 S.8'\n"
"    ],\n"
"    'priority': ['Must Have','Must Have','Must Have','Must Have','Should Have','Should Have']\n"
"}\n"
"\n"
"df_nfr = pd.DataFrame(nfr_data)\n"
"print('Non-functional requirements:', len(df_nfr))\n"
"df_nfr[['req_id','category','title','priority']]\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 4. Requirements Backlog - MoSCoW Prioritisation\n"
"\n"
"| Priority | Definition |\n"
"|----------|------------|\n"
"| **Must Have** | Non-negotiable. Regulatory requirement or blocking risk. |\n"
"| **Should Have** | Important but can be deferred with risk. |\n"
"| **Could Have** | Desirable. Do if time allows. |\n"
"| **Won't Have** | Explicitly excluded from this sprint. |\n"
))

cells.append(nbf.v4.new_code_cell(
"# Build backlog table\n"
"df_fr['type'] = 'FR'\n"
"df_nfr['type'] = 'NFR'\n"
"\n"
"# Combine into backlog\n"
"df_backlog = pd.concat([\n"
"    df_fr[['req_id','title','type','priority','dependencies']],\n"
"    df_nfr[['req_id','title','category','type','priority']].rename(columns={'category':'title'})\n"
"], ignore_index=True)\n"
"\n"
"# T-shirt effort sizing\n"
"effort = {'Must Have':'M','Should Have':'M','Could Have':'S',\"Won't Have\":'S'}\n"
"df_backlog['estimated_effort'] = df_backlog['priority'].map(effort)\n"
"\n"
"# Sprint assignment\n"
"sprint_map = {'Must Have':'Sprint 1','Should Have':'Sprint 2','Could Have':'Backlog',\"Won't Have\":'Out of Scope'}\n"
"df_backlog['assigned_sprint'] = df_backlog['priority'].map(sprint_map)\n"
"\n"
"print('MERIDIAN FINANCIAL - REQUIREMENTS BACKLOG')\n"
"print('='*55)\n"
"for sprint in ['Sprint 1','Sprint 2','Backlog']:\n"
"    subset = df_backlog[df_backlog['assigned_sprint']==sprint]\n"
"    if len(subset)>0:\n"
"        print()\n"
"        print(sprint.upper() + ' (' + str(len(subset)) + ' items)')\n"
"        print('-'*50)\n"
"        for _, row in subset.iterrows():\n"
"            t = '[FR]' if row['type']=='FR' else '[NFR]'\n"
"            print('  ' + row['req_id'] + ' ' + t + ' - ' + row['title'][:55])\n"
))

cells.append(nbf.v4.new_markdown_cell("## 5. Gap-to-Requirement Traceability\n"))

cells.append(nbf.v4.new_code_cell(
"# Verify every gap has a mapped requirement\n"
"trace = []\n"
"for _, gap in df_gaps.iterrows():\n"
"    matched = df_fr[df_fr['source_gap']==gap['gap_id']]['req_id'].tolist()\n"
"    if not matched:\n"
"        matched = ['WARNING: NO FR MAPPED - ADD REQUIREMENT']\n"
"    for fr in matched:\n"
"        trace.append({'gap_id':gap['gap_id'],'gap_name':gap['gap_name'],'severity':gap['severity'],'req_id':fr})\n"
"\n"
"df_trace = pd.DataFrame(trace)\n"
"\n"
"print('GAP TO REQUIREMENT TRACEABILITY')\n"
"print('='*55)\n"
"for gid, grp in df_trace.groupby('gap_id'):\n"
"    print(gid + ' (' + grp['severity'].iloc[0] + ') -> ' + ', '.join(grp['req_id'].tolist()))\n"
"\n"
"unmapped = df_trace[df_trace['req_id'].str.startswith('WARNING')]\n"
"if len(unmapped)>0:\n"
"    print()\n"
"    print('WARNING: Unmapped gaps:')\n"
"    print(unmapped[['gap_id','gap_name']].to_string(index=False))\n"
"else:\n"
"    print()\n"
"    print('All gaps mapped to at least one requirement.')\n"
))

cells.append(nbf.v4.new_markdown_cell("## 6. Requirements Review Notes\n"))

cells.append(nbf.v4.new_code_cell(
"# COMPLETE THIS SECTION\n"
"review_notes = '''\n"
"REQUIREMENTS REVIEW NOTES - Task 2 Self-Review\n"
"================================================\n"
"\n"
"CONFLICTS IDENTIFIED:\n"
"[Document any conflicts between requirements here]\n"
"\n"
"OPEN QUESTIONS FOR ENGINEERING (Diana Vlasova):\n"
"1. [e.g. Can Salesforce FSC store a BO record with required fields?]\n"
"2. [e.g. Does the Onboarding Microservice handle real-time Dow Jones API calls?]\n"
"3. [e.g. What is the fallback if the Experian API is unavailable?]\n"
"\n"
"OPEN QUESTIONS FOR COMPLIANCE (Sarah Chen):\n"
"1. [e.g. Is a 30-second timeout acceptable given Consumer Duty?]\n"
"2. [e.g. What risk score threshold defines Medium risk?]\n"
"\n"
"AI OUTPUT REVIEW:\n"
"[Note which AI-generated requirements you changed and why]\n"
"\n"
"RISK NOTE:\n"
"Sprint 1 is extremely ambitious. Engineering flagged the Salesforce FSC sync with the\n"
"microservice as the biggest technical risk. Consider descoping FR-004 and FR-005 to\n"
"Sprint 2 if timeline slips.\n"
"'''\n"
"print(review_notes)\n"
))

cells.append(nbf.v4.new_markdown_cell("## 7. Export\n"))

cells.append(nbf.v4.new_code_cell(
"df_fr.to_csv('../outputs/functional_requirements.csv', index=False)\n"
"df_nfr.to_csv('../outputs/non_functional_requirements.csv', index=False)\n"
"df_backlog.to_csv('../outputs/requirements_backlog.csv', index=False)\n"
"df_trace.to_csv('../outputs/gap_requirement_traceability.csv', index=False)\n"
"\n"
"print('Exported:')\n"
"for f in ['functional_requirements.csv','non_functional_requirements.csv',\n"
"          'requirements_backlog.csv','gap_requirement_traceability.csv']:\n"
"    print('  -',f)\n"
))

cells.append(nbf.v4.new_markdown_cell(
"## 8. AI Prompt Library - Task 2\n"
"\n"
"---\n"
"\n"
"### Prompt 2.1: User Story Generation\n"
"\n"
"```\n"
"You are a Senior Business Analyst writing user stories for a UK fintech onboarding remediation.\n"
"\n"
"Gap: [paste gap description and regulatory reference]\n"
"\n"
"Write 3 user stories. Format:\n"
"Title: As a [ROLE] I want [capability] so that [outcome]\n"
"\n"
"Acceptance Criteria (min 3, Given/When/Then):\n"
"- Given [precondition] when [action] then [observable result]\n"
"\n"
"Also note: regulatory address, failure risk, test scenario.\n"
"```\n"
"\n"
"### Prompt 2.2: NFR Generation\n"
"\n"
"```\n"
"You are a Financial Services Technology Architect.\n"
"\n"
"Generate NFRs for a UK fintech onboarding system (KYC/AML, FCA-regulated, Salesforce FSC + Microservice + Experian + Dow Jones).\n"
"\n"
"Categories: Performance, Security, Availability, Compliance, Usability, Scalability.\n"
"\n"
"For each NFR: specific and measurable standard, how to test it, and regulatory reference.\n"
"```\n"
"\n"
"### Prompt 2.3: Conflict Detection\n"
"\n"
"```\n"
"Review these requirements and identify: conflicts, external dependencies, unrealistic items for 10-week delivery, and acceptance criteria that are not testable.\n"
"\n"
"[paste requirements list]\n"
"```\n"
))

nb.cells = cells
with open('/opt/data/capstone/notebooks/Task_2_Requirements_Engineering.ipynb', 'w') as f:
    nbf.write(nb, f)
print("Task 2 notebook written OK")
